version: '3.8'

services:
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: ojt_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    # env_file:
    #   - ./BE/.env

  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    container_name: ojt_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
